### ISSUE TITLE
Display error message for unsupported browsers

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/react-components#129]
IE11 and old Safari (under than version 10).

**Comment by mmso** [comment]
I realised we probably want to remove IE11 as a babel compilation target, which means the whole bundle would throw an error. We'd need another way than using the `CompatibilityCheck` component to display that the browser is not supported.

**Comment by mmso** [comment]
Done in https://github.com/ProtonMail/react-components/commit/76a5fb6c82f869038576ae4baa744a800ce2e042
