### ISSUE TITLE
Tooltip in JS

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/react-components#135]
We currently manage Tooltip with CSS but it doesn't work very well. 

<img width="615" alt="Capture d’écran 2019-07-25 à 16 08 50" src="https://user-images.githubusercontent.com/1345786/61881208-8484e300-aef6-11e9-85d0-c86253943c76.png">

If we cannot fix it with CSS, we need to think our proper solution in JS.

- Since the `Tooltip` is used in different places, it needs to keep the same signature.
- Managing automatic is a plus but not a requirement for the first version.

**Comment by mmso** [comment]
![Screenshot 2019-07-26 at 10 15 35](https://user-images.githubusercontent.com/352607/61937078-594dd280-af8e-11e9-9053-8e179ea535c0.png)

Same problem with dropdown so let's fix that too
