### ISSUE TITLE
Block actions of parent modal when a child modal is opened

### ISSUE THREAD

**Issue by econdepe** [ProtonMail/react-components#146]
Right now, if a (child) modal is created from another (parent) modal, although the parent modal acquires the class `pm-modal--inBackground`, the buttons of the parent modal are still clickable, which can wreak havoc.

![image](https://user-images.githubusercontent.com/33841139/62047882-cde17500-b20b-11e9-9172-ff0f21058506.png)

It could also be nice to have the parent modal get a darker tone, like what happens to the background when a modal is opened.

**Comment by mmso** [comment]
This is fixed with the recent z-index changes
