### ISSUE TITLE
The real checkbox is not synced with the fake one.

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/react-components#149]
**Summary**
The toggle component is implemented as checkbox + labels, for better ui. However, when I switch the toggle the dom is not updated.
 
**Example:**
Under `settings/general`, the request link confirmation always says checked and the Sent/Drafts doesn't include the checked attribute.

**Video:** https://recordit.co/UekzIK0Uwk

**Comment by EpokK** [comment]
I tested and the component state looks correct when I'm checking with [React dev tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi):
<img width="991" alt="Capture d’écran 2019-07-31 à 08 39 49" src="https://user-images.githubusercontent.com/1345786/62189249-cc7c8d80-b36e-11e9-99eb-b29722b5fe0b.png">
<img width="919" alt="Capture d’écran 2019-07-31 à 08 39 55" src="https://user-images.githubusercontent.com/1345786/62189250-cc7c8d80-b36e-11e9-8cc4-2d9d63c2a793.png">
