### ISSUE TITLE
Dropdowns inside modals not displaying

### ISSUE THREAD

**Issue by econdepe** [ProtonMail/react-components#165]
When a dropdown is inside a modal, its content is hidden behind the modal (apparently dropdown has `z-index = 10` plus a fixed position while the modal has `z-index = 666`).

I'm using the `DropdownActions` component which uses the new dropdowns. See attached pictures below:
![image](https://user-images.githubusercontent.com/33841139/62552203-8abb7d80-b86d-11e9-8687-af60095e7ed9.png)
![image](https://user-images.githubusercontent.com/33841139/62552289-b0488700-b86d-11e9-8737-a4ba9e8aae77.png)

According to @nico3333fr , one good solution would be for the dropdown to detect that it's been opened inside a modal, then set a `z-index > 666`. If setting a `z-index > 666` one could run into other unexpected problems if the dropdown is opened simultaneously with other elements, although these are unlikely situations

**Comment by mmso** [comment]
We should render the modals in a portal too, so they are rendered as siblings to the drop downs and render them both at the same z-index, given that everything is inserted in order it should be ok.
