### ISSUE TITLE
The address status is not automatically updated

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/react-components#25]
**Steps to reproduce**
1. Load the AddressesSection
2. Change the status of the address.(Ex: enable, disable)

**Expected behavior**
The new status of the address should be shown.

**Screenshot**
![addressStatus](https://user-images.githubusercontent.com/11393457/55177906-9e026200-5184-11e9-90d7-71fd032a9cbf.gif)

**Comment by EpokK** [comment]
The code is setup, it's just because the eventManager hook is not yet ready.
