### ISSUE TITLE
The page selector from the pagination component should have limited height

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/react-components#26]
1. Load any part of the app that has pagination component with lots of pages. (Ex: security logs).
2. Click to select a page from the paginatior.
3. Notice how the page selector can take over the page. 

**Expected behavior**
If there are lots of pages to be selected from(ex: 50+), the page selector should have a scrollbar, and have limited height.
Should be similar to the current ProtonMail implementation.
![sc](https://user-images.githubusercontent.com/11393457/55233164-f8a0ca00-5227-11e9-83ee-275b1332bc1c.png)

**Current behavior**
![PagingDesign](https://user-images.githubusercontent.com/11393457/55233211-271ea500-5228-11e9-9608-af2672eab4e8.gif)

**Comment by RandomAdversary** [comment]
Tested, this one is not fixed.

![Pagination](https://user-images.githubusercontent.com/11393457/58565858-c6afe200-822f-11e9-822d-1316090c066a.gif)

**Comment by mmso** [comment]
Done in https://github.com/ProtonMail/react-components/commit/392dcd25ddf0b6d1ecf6fb19042c137778b20d85
