### ISSUE TITLE
Checkbox animations are triggered on all checkboxes at once

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/react-components#28]
**Steps to reproduce**
1. Load the NewsCheckboxes section.
2. Change the state of any checkbox
3. Notice how every checkbox gets an animation.

**Screenshot**
![chkBox](https://user-images.githubusercontent.com/11393457/55244799-2a268f00-5242-11e9-98e4-c41498eb6a63.gif)

**Additional info**
This was tested only on NewsCheckboxes section. I'm not sure if the problem occurs in other places.

**Comment by EpokK** [comment]
Yeah that's expected, we disable checkboxes when an API request is running.
