### ISSUE TITLE
[I18n] suggestion for improvement- deleteKeyModal

### ISSUE THREAD

**Issue by dhoko** [ProtonMail/react-components#320]
https://github.com/ProtonMail/react-components/blob/master/containers/keys/deleteKey/DeleteKeyModal.js#L89

From `We are now deleting the key for your address.`
To: ` The key for your address is now being deleted.`

via [crowdin](https://crowdin.com/translate/protonmail/42/en-ru#34560)

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/pull/346
