### ISSUE TITLE
V4 extra polish - Add tooltip to app menu

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/react-components#366]
See what @dhoko did for Mail.

![Screenshot from 2019-10-21 17-55-25](https://user-images.githubusercontent.com/40168570/67265220-8175a080-f4ad-11e9-8fa8-87f08c10c06d.png)

**Comment by EpokK** [comment]
Done with https://github.com/ProtonMail/react-components/commit/54f1ac4ad5833665695ec9973148830d56820579
