### ISSUE TITLE
Update the account drop down menu to match what we did in Angular

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/react-components#396]
Angular screenshot (correct)
<img width="383" alt="Capture d’écran 2019-10-28 à 18 28 38" src="https://user-images.githubusercontent.com/40168570/67701813-ec910c80-f9b0-11e9-81de-9b6d01e1d148.png">

React screenshot (outdated)
<img width="419" alt="Capture d’écran 2019-10-28 à 18 28 22" src="https://user-images.githubusercontent.com/40168570/67701834-f4e94780-f9b0-11e9-873c-84fa388eabc4.png">

**Comment by matstaz** [comment]
I know why we have settings here. let's just remove it for the time being until we sort it out.

We can keep the tutorial only for mailbox.

**Comment by EpokK** [comment]
Close this issue since recent change on Angular side.
