### ISSUE TITLE
Add calendar link in sidebars

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/react-components#406]
To let people access to the calendar, we need to add back the link icon in the `<AppSidebar>` component and `<Sidebar>` of `proton-contacts` + `proton-calendar` + `proton-mail-settings`. 

- Check with Delong if we have to add a display condition on it.
- Check with @matstaz for the icon to use.
- For the sidebar in `proton-calendar`, ping me and I will do it.

![Capture d’écran 2019-10-31 à 12 01 28](https://user-images.githubusercontent.com/1345786/67941579-39a1f800-fbd6-11e9-8f4b-b45ced563288.png)
![Capture d’écran 2019-10-31 à 12 01 38](https://user-images.githubusercontent.com/1345786/67941580-3a3a8e80-fbd6-11e9-8fef-058de89536a9.png)

**Comment by Swiip** [comment]
I opened 4 PRs:
- `react-components` for the desktop sidebar in all React apps
- `proton-mail-settings` for the mobile sidebar in settings
- `proton-contacts` for the mobile sidebar in settings
- `Angular` for the desktop and mobiles sidebars in Angular

Left to do: `proton-calendar`.
