### ISSUE TITLE
Restrict the color picker to a limited pool of color

### ISSUE THREAD

**Issue by EpokK** [ProtonMail/react-components#422]
Review the `ColorPicker` component to simplify it with a pool of colors. Right now, we are using a library for it, just remove it and revamp the component.

### Design
https://app.zeplin.io/project/5d3afcab62259b6cb60d7059/screen/5dc5773ae1948c239cc62dd7

### Note
- In the case the initial color doesn't exist in the pool, just display it as selected but don't add a new color in the dropdown.

Reported by Aude

**Comment by gledunProton** [comment]
Reuse the same picker as folder component in ProtonMail
