### ISSUE TITLE
Date picker bugs & quick wins

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/react-components#423]
- [x] Month/year should be centered
- [x] Arrows to move to previous month/next month should be visible (i cannot select another month unless I manually replace `Nov` by `Dec` or `Jan` in the text input
- [x] today's date could be highlighted with primary blue
- [x] clicking on a date does not select it and close the date picker (it would probably require a click effect and then automatically close)
- [x] add padding

here is the design direction: https://app.zeplin.io/project/5d3afcab62259b6cb60d7059/screen/5dbc40ba03012e5571e751ff

here is what I currently experience in FF on Mac OSX
<img width="703" alt="Capture d’écran 2019-11-06 à 20 36 48" src="https://user-images.githubusercontent.com/40168570/68368509-7cb11d80-0138-11ea-95d3-1b2dfb2ea0eb.png">

**Comment by EpokK** [comment]
> Month/year should be centered

No.
