### ISSUE TITLE
Update the app bar icon for Calendar & Contacts

### ISSUE THREAD

**Issue by matstaz** [ProtonMail/react-components#451]
Update the icon that appears in the sidebar with a calendar shape

PM + Design: Review the coming soon options designed

For contacts:
[Contact icon.svg.zip](https://github.com/ProtonMail/react-components/files/3977132/Contact.icon.svg.zip)

For calendar:
[Calendar icon.svg.zip](https://github.com/ProtonMail/react-components/files/3977115/Calendar.icon.svg.zip)

**Comment by econdepe** [comment]
I see that the contacts app bar icon has the size 14x16. @nico3333fr , do you know if we need square (16x16) icons?

**Comment by nico3333fr** [comment]
Yes, small icons should always be 16x16 viewbox, @matstaz could you send us a "fixed" version please?

**Comment by matstaz** [comment]
@econdepe should both be in 16x16 and the calendar issue should have been fixed.

**Comment by nico3333fr** [comment]
Done on Design system. https://github.com/ProtonMail/design-system/commit/cd903a374d4828d8f88a7660d8f0a1ddc3ef8de0
https://github.com/ProtonMail/design-system/commit/36b7b84dd6eee949c67933d3e8e1b1c10c9faa22
