### ISSUE TITLE
When payment amount is <5, payment method resets to default

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [ProtonMail/react-components#454]
**CS Report**
https://proton.atlassian.net/browse/CLIENT-1905

**Steps to reproduce**
1. go to settings and  click add credits
2. select bitcoin
3. enter an amount below 5,
4. the payment method disappears
5. enter a valid amount
6. credit card is selected by default.

**Expected behavior**
Bitcoin payment method to be selected.

**Video**
https://recordit.co/qGWE59OSGf

**Comment by EpokK** [comment]
Fixed in https://github.com/ProtonMail/react-components/pull/448
