### ISSUE TITLE
Certain display names are not shown properly in the header

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [ProtonMail/react-components#474]
**Steps to reproduce**
1. Login
2. Change display name to `22 - Name`
3. Notice the display name in the header

**Expected behavior**
The initials circle should contain `22`

**Screenshot**
![image](https://user-images.githubusercontent.com/11393457/70129275-b7966a80-167e-11ea-845e-fb60096f0a35.png)

**Comment by EpokK** [comment]
> The initials circle should contain 22

No it should be `2N`.
