### ISSUE TITLE
When the current page is empty, the paginator doesn't return to the previous page

### ISSUE THREAD

**Issue by RandomAdversary** [ProtonMail/react-components#91]
**Steps to reproduce**
1. Open 11 sessions to a account.
2. Add sessions component
3. Go to second page of the sessions table.
4. Revoke the last session.

**Expected behavior**
The session should be revoked. Previous page should be shown.

**Screenshot**
![RevSe](https://user-images.githubusercontent.com/11393457/58631917-49927480-82e4-11e9-85ec-c479775f2e91.gif)

**Comment by mmso** [comment]
Fixed in https://github.com/ProtonMail/react-components/commit/0f3ab56b5da92c6aa5594c844de7888c844075bd
