### ISSUE TITLE
Erase deprecated useModal.js

### ISSUE THREAD

**Issue by econdepe** [ProtonMail/react-components#96]
After PR #68 [this file](https://github.com/ProtonMail/react-components/blob/master/components/modal/useModal.js) is deprecated.

Do we need to keep it for something (it's not used anymore nor in this repo nor in `protonmail-settings`)? Otherwise it's maybe better to remove it since it can cause confusion.

**Comment by EpokK** [comment]
Yeah we can remove it @econdepe
